version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/telemetry-worker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gomod"
    directory: "/provisioning-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10